const products = [
  {
    _id: "1",
    name: "Airpods Wireless Bluetooth",
    image: "/images/airpods.jpg",
    description:
      "Automatically on, automatically connected,Easy setup for all your Apple devices.Double-tap to play or skip forward",
    brand: "Apple",
    category: "Electronics",
    price: 89.99,
    countInStock: 3,
    rating: 4.5,
    numReviews: 4,
  },
  {
    _id: "2",
    name: "Alexa Wireless Bluetooth",
    image: "/images/alexa.jpg",
    description:
      "Voice control your entertainment - Stream songs from Amazon Music, Apple Music, Spotify, SiriusXM, and others. Play music, audiobooks, and podcasts throughout your home with multi-room music.",
    brand: "Echo",
    category: "Electronics",
    price: 49.99,
    countInStock: 2,
    rating: 4.7,
    numReviews: 8,
  },
  {
    _id: "3",
    name: "Nikon Special Effects 128MP",
    image: "/images/camera.jpg",
    description:
      "Auto, Landscape, Special Effects Modes (night vision; super vivid; pop; photo illustration; toy camera effect; miniature effect; selective color; silhouette; high key; low key), Night Portrait, Portrait, Auto [Flash Off], Close-up, Child, Sports",
    brand: "Nikon",
    category: "Electronics",
    price: 189.99,
    countInStock: 7,
    rating: 4.1,
    numReviews: 14,
  },
  {
    _id: "4",
    name: "Logitech G502 SE Hero High Performance RGB ",
    image: "/images/mouse.jpg",
    description:
      "High performance hero 16k sensor: Logitech most accurate sensor yet with upto 16,000 dpi for the ultimate in gaming speed, accuracy and responsiveness across entire dpi range",
    brand: "Logitech",
    category: "Electronics",
    price: 29.99,
    countInStock: 13,
    rating: 4.0,
    numReviews: 5,
  },
  {
    _id: "5",
    name: "Huawei Honor 8X (64GB + 4GB RAM) 6.5 HD 4G LTE GSM",
    image: "/images/phone.jpg",
    description:
      "4G LTE bands 1(2100), 2(1900), 3(1800), 4(1700/2100), 5(850), 7(2600), 28(700), 4G LTE tdd: B41, 3G WCDMA: B1/B2/B4/B5/B8, 2G GSM: B2/B3/B5/B8 - Dual SIM (nano-sim, Dual stand-by) check compatibility with your carrier before purchase. North and south American 4G LTE compatible",
    brand: "Huawei",
    category: "Electronics",
    price: 289.99,
    countInStock: 54,
    rating: 4.2,
    numReviews: 124,
  },
  {
    _id: "6",
    name: "PlayStation 5 Console",
    image: "/images/ps5.jpg",
    description:
      "Lightning Speed - Harness the power of a custom CPU, GPU, and SSD with Integrated I/O that rewrite the rules of what a PlayStation console can do",
    brand: "Sony",
    category: "Electronics",
    price: 489.99,
    countInStock: 0,
    rating: 5,
    numReviews: 40,
  },
];
export default products